/* tabla temporal */
CREATE TABLE historico_cobros_temporal2
(
usuario_consulta VARCHAR2(2),
fecha_consulta DATE,
agente VARCHAR2(15),
banco_csb_cheque NUMBER(19, 4),
codigo_cuenta VARCHAR2(15),
diario VARCHAR2(4),
divisa_origen VARCHAR2(4),
documento_agrupado VARCHAR2(1),
empresa VARCHAR2(5),
endoso VARCHAR2(1),
estado VARCHAR2(4),
estado_csb_cheque VARCHAR2(4),
fecha_remesa DATE,
fecha_valor_divisa DATE,
fecha_vencimiento_original DATE,
forma_cobro VARCHAR2(4),
gastos_devolucion NUMBER(19, 4),
gastos_protesto NUMBER(19, 4),
gastos_reclamacion NUMBER(19, 4),
importe_cobrado_divisa NUMBER(19, 4),
importe_compensado NUMBER(19, 4),
importe_descuento_pronto_pago NUMBER(19, 4),
importe_divisa NUMBER(19, 4),
importe_endosado NUMBER(19, 4),
importe_impagado NUMBER(19, 4),
importe_impagado_divisa NUMBER(19, 4),
importe_recargo_financiero NUMBER(19, 4),
importe_sustituido_divisa NUMBER(19, 4),
justificante VARCHAR2(100),
marca_punteo VARCHAR2(2),
num_cheque NUMBER(19, 4),
numero_asiento_borrador NUMBER(19, 4),
numero_direccion NUMBER(19, 4),
numero_linea_borrador NUMBER(19, 4),
numero_remesa NUMBER(19, 4),
repercutido_factura VARCHAR2(1),
seguro_cambio NUMBER(19, 4),
seguro_cobro VARCHAR2(1),
serie_justificante VARCHAR2(4),
situacion_apunte VARCHAR2(1),
status_aceptado VARCHAR2(1),
status_contabilizado VARCHAR2(1),
status_impagado VARCHAR2(1),
status_impresion VARCHAR2(1),
status_reclamacion VARCHAR2(1),
status_remesado VARCHAR2(1),
tipo_transaccion VARCHAR2(4),
usuario VARCHAR2(10),
codigo_cliente_endoso VARCHAR2(15),
numero_direccion_endoso NUMBER(19, 4),
caracter_asiento VARCHAR2(4),
factoring VARCHAR2(1),
status_retenido VARCHAR2(1),
numero_poliza NUMBER(19, 4),
codigo_banco VARCHAR2(15),
codigo_cliente VARCHAR2(15),
fecha_factura DATE,
fecha_vencimiento DATE,
fecha_asiento DATE,
documento VARCHAR2(100),
concepto VARCHAR2(100),
importe NUMBER(19, 4),
importe_sustituido NUMBER(19, 4),
importe_cobrado NUMBER(19, 4),
documento_vivo VARCHAR2(1),
numero_expediente NUMBER(19, 4);
);

[14:36] Jose Carlos Diaz Pantoja
no puedo ejecutar ese create table :c

