/*** procedmiento para generar la cartera reconstruida - a demanda  ***/
BEGIN
reconstruida.cobros('JCDIAZ', TO_DATE('14/10/2022','DD/MM/YYYY'), '004', TO_DATE('30/09/2022','DD/MM/YYYY'), '', '');
END;

SELECT
DISTINCT
decode(C.ZONA,'0410','SCZ','0420','LPZ','0430','CBBA','0440','TJA','0450','ALTO','0451','ALTO','0460','SCR','0461','SCR','0470','BENI','0471','BENI','SIN REG') REG, CADENA.NOMBRE_CADENA, CANAL_VENTA.CANAL_VENTA, RPN3.RPN_COBRANZA,
DT.CODIGO_CLIENTE, C.NOMBRE,DT.FECHA_FACTURA, DT.FECHA_VENCIMIENTO, DT.FECHA_ASIENTO, DT.DOCUMENTO, DT.CONCEPTO, DT.IMPORTE, DT.IMPORTE_SUSTITUIDO , DT.IMPORTE_COBRADO, DT.DOCUMENTO_VIVO
FROM
(SELECT CODIGO_CLIENTE, FECHA_FACTURA, FECHA_VENCIMIENTO, FECHA_ASIENTO,DOCUMENTO, CONCEPTO, IMPORTE, IMPORTE_SUSTITUIDO, IMPORTE_COBRADO, DOCUMENTO_VIVO  
FROM HISTORICO_COBROS_TEMPORAL
) DT, CLIENTES C, (    SELECT CCE.CODIGO_CLIENTE AS CODIGO_CLIENTE,VC.NOMBRE AS NOMBRE_CADENA    FROM CLIENTES_CLAVES_ESTADISTICAS CCE, VALORES_CLAVES VC    WHERE CCE.CLAVE=VC.CLAVE AND CCE.VALOR_CLAVE=VC.VALOR_CLAVE AND CCE.CLAVE='CADN') 
CADENA,(    SELECT CCE.CODIGO_CLIENTE AS CODIGO_CLIENTE,VC.NOMBRE AS CANAL_VENTA    FROM CLIENTES_CLAVES_ESTADISTICAS CCE, VALORES_CLAVES VC    WHERE CCE.CLAVE=VC.CLAVE AND CCE.VALOR_CLAVE=VC.VALOR_CLAVE AND CCE.CLAVE='CANALV')
CANAL_VENTA,(    SELECT V_CLAVE AS CLAVE,V_VALOR_CLAVE AS CODIGO_RPN,D_VALOR_CLAVE AS RPN_COBRANZA,CODIGO_CLIENTE     FROM (        SELECT clientes_claves_estadisticas.* ,(            SELECT lvce.nombre             FROM claves_estadisticas lvce             WHERE lvce.clave = clientes_claves_estadisticas.clave) D_CLAVE,                (SELECT lvc.nombre                 FROM valores_claves lvc                 WHERE lvc.clave = clientes_claves_estadisticas.clave AND lvc.valor_clave = clientes_claves_estadisticas.valor_clave) D_VALOR_CLAVE,CLAVE V_CLAVE,VALOR_CLAVE V_VALOR_CLAVE,VALOR_NUMERICO V_VALOR_NUMERICO         FROM clientes_claves_estadisticas        ) clientes_claves_estadisticas     WHERE (CODIGO_EMPRESA='004')  AND V_CLAVE='RPN3'
) RPN3
WHERE DT.CODIGO_CLIENTE=C.CODIGO_RAPIDO and C.CODIGO_EMPRESA='004'AND CADENA.CODIGO_CLIENTE=DT.CODIGO_CLIENTE AND CANAL_VENTA.CODIGO_CLIENTE=DT.CODIGO_CLIENTE AND RPN3.CODIGO_CLIENTE=DT.CODIGO_CLIENTE /*AND DT.CODIGO_CLIENTE='008798'*/
ORDER BY REG, NOMBRE_CADENA, CANAL_VENTA, RPN_COBRANZA, CODIGO_CLIENTE, FECHA_VENCIMIENTO

